version: '3.4'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: randompassword
      POSTGRES_USER: johndoe
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    networks:
      - stefanini-network
networks:
  stefanini-network:
    driver: bridge
