org: focadecombate
app: my-aws-node-express-api-app
service: my-aws-node-express-api-app

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

custom:
  serverless-offline:
    noPrependStageInUrl: true
    host: localhost

package:
  patterns:
    - '!./**'
    - '!.husky/**'
    - '!src/**'
    - 'dist/**'
    - '!node_modules/.prisma/client/query-engine-*'
    - 'node_modules/.prisma/client/query-engine-rhel-*'
    - 'node_modules/**'

functions:
  api:
    handler: dist/main/handler.handler
    environment:
      DATABASE_URL: ${param:database, "postgresql://johndoe:randompassword@localhost:5432/mydb?schema=public"}

    events:
      - http:
          path: / # this matches the base path
          method: ANY
      - http:
          path: /{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY

plugins:
  - serverless-offline
